SE-35: Refactor the API endpoints response
mobile-apcs-ntploc21/mobile-backend pull request #65
Opened 2024-11-03 14:37 UTC by RLukas2

# What?
This pull request refactors API endpoints that currently return singular elements directly to return consistent list responses. This improves the API's consistency and simplifies data handling on the front end.

This PR also sorts the Unicode emojis list response so the front end can easily fetch and use it instantly instead of taking another step of sorting.

## What's New?
- Refactored Endpoints: Modified the specified API endpoints to wrap singular elements in a list.
- Unicode emojis: Modified the Apollo backend so it will sort the Unicode result to default that the CLDR project has been using.

# API Endpoints
## GET /api/v1/servers/emojis/user/:userId
Response Body:
```json
{
  "categories": [
    {
      "name": "Server A",
      "server_id": "66d16d04f11df0075706486c",
      "emojis": [
        {
          "id": "6719045e299b614e0f79ccee",
          "name": "emoji_A",
          "image_url": "https://cdn.example.com/emojis/668ff7ec32d433337fe2da8b",
          "uploader_id": "668ff7ec32d433337fe2da8b"
        }
      ]
    },
    {
      "name": "Server B",
      "server_id": "66d170eb64dfa810c5b6ae6e",
      "emojis": []
    },
  ]
}
```

## GET api/v1/servers/list
Response Body:
```json
{
  "servers": [
    {
      "id": "66d16d04f11df0075706486c",
      "owner": "668ff7ec32d433337fe2da8b",
      "name": "Server A",
      "avatar_url": "https://cdn.example.com/assets/14764177?1724653052.jpeg",
      "banner_url": "https://cdn.example.com/assets/3f8cb71e0a27876a793926a05687db47acd9c4a460378077c44b89a54ce139f8.jpeg",
      "totalMembers": 11,
      "totalEmojis": 1,
      "is_favorite": false,
      "position": 0
    },
    {
      "id": "66d170eb64dfa810c5b6ae6e",
      "owner": "668ff7ec32d433337fe2da8b",
      "name": "Server B",
      "avatar_url": "",
      "banner_url": "",
      "totalMembers": 1,
      "totalEmojis": 0,
      "is_favorite": false,
      "position": 1
    }
  ]
}
```
## GET /api/v1/servers/emojis/unicode
Response Body:
```json
{
  "categories": [
    {
      "name": "People",
      "emojis": [
        {
          "id": "671903c4d93ecdaf1e2c010f",
          "name": "grinning",
          "unicode": "😀"
        },
        {
          "id": "671903c4d93ecdaf1e2c0112",
          "name": "smiley",
          "unicode": "😃"
        },
        {
          "id": "671903c4d93ecdaf1e2c0113",
          "name": "smile",
          "unicode": "😄"
        },
      ]
    }
  ]
]

2024-11-04 22:53 UTC, ntploc21 approved these changes
LGTM!

2024-11-04 22:57 UTC, ntploc21 commented
Hi @RLukas2, could you help me add swagger docs for the API endpoints implemented for this PR? We have now deployed and used the API swagger document. This will help reduce the developer's effort in finding the API request & response format.
Thanks!

2024-11-04 22:58 UTC, ntploc21 requested changes
Hi @RLukas2, could you help me add swagger docs for the API endpoints implemented for this PR? We have now deployed and used the API swagger document. This will help reduce the developer's effort in finding the API request & response format.
Thanks!

2024-11-14 13:09 UTC, ntploc21 approved these changes

2024-11-14 13:09 UTC, ntploc21 submitted a review, later dismissed

2024-11-14 13:10 UTC, ntploc21 approved these changes

2024-11-14 13:12 UTC, ntploc21 submitted a review, later dismissed

2024-11-14 13:12 UTC, ntploc21z submitted a review, later dismissed

2024-11-14 13:35 UTC, ntploc21 approved these changes

2024-11-14 13:45 UTC, merged